import { LegalPage } from "@/components/legal";
import { pageMeta } from "@/lib/seo";

export const metadata = pageMeta({ title: "Privacy policy", description: "How CorpGurus collects, uses, shares and protects personal data of trainers, company users and participants, in line with India's Digital Personal Data Protection Act, 2023.", path: "/legal/privacy" });

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy policy" effective="1 October 2026" current="privacy"
      intro={<p>This policy explains what personal data CorpGurus collects, why, who it is shared with and the choices you have. It is written to meet India’s Digital Personal Data Protection Act, 2023 and applies to trainers, company users, training participants who receive feedback links or certificates, and visitors.</p>}
      sections={[
        { id: "data", title: "Data we collect", body: <><ul><li><strong>Account data:</strong> name, email, password hash, phone (optional), time zone, language, profile photo, role.</li><li><strong>Trainer profile:</strong> headline, bio, skills, cities, delivery modes, day rates, certifications and the documents you upload to verify them, work history, courses, gallery photos, availability, bank/payment details for invoices, GSTIN.</li><li><strong>Company data:</strong> company name, website, industry, size, logo, GSTIN, billing address, team members.</li><li><strong>Activity:</strong> requirements, applications, comments, posts, messages and attachments, ratings, recommendations, work orders and typed signatures, invoices, escrow records, saved searches, notifications.</li><li><strong>Participants:</strong> when a company or trainer issues certificates or feedback links, we hold participant names and (if given) email addresses, and anonymous feedback responses.</li><li><strong>Technical:</strong> IP address, browser and device information, pages visited, push-notification subscriptions, and cookies needed to keep you signed in and remember your language.</li><li><strong>Sign-in with Google or LinkedIn:</strong> your name, email and profile photo from the provider. We do not receive your provider password.</li></ul></> },
        { id: "use", title: "How we use it", body: <><ul><li>To run the marketplace: show profiles and requirements, match trainers to requirements, deliver messages and notifications, generate work orders, invoices and certificates.</li><li>To verify certifications and company domains, and to display badges based on that verification.</li><li>To process payments and escrow through Razorpay and Stripe, and to send billing emails.</li><li>To send transactional email, WhatsApp/SMS and push notifications you have enabled. Marketing email is sent only with consent and always has an unsubscribe link.</li><li>To keep the Platform secure: rate limiting, fraud and abuse detection, audit logs of staff actions.</li><li>To improve the Platform using aggregated, de-identified usage statistics.</li></ul></> },
        { id: "sharing", title: "Who sees your data", body: <><ul><li><strong>Other users.</strong> Trainer profiles are public except day rates (signed-in companies only), contact details and payment details. Public requirements are visible to everyone; invite-only requirements only to invited trainers. Company members see applications to their requirements. Certificates are public at their verification link.</li><li><strong>Service providers</strong> acting on our instructions: hosting (Hetzner, EU/India), database backups, Resend (email), Twilio (WhatsApp/SMS), Razorpay and Stripe (payments), S3-compatible object storage (uploads), Google and LinkedIn (sign-in only when you choose them).</li><li><strong>Training partners using the API</strong> receive data only about their own requirements, applications and work orders.</li><li><strong>Legal requirements:</strong> we disclose data when required by law or to protect users and the Platform.</li><li>We do not sell personal data.</li></ul></> },
        { id: "retention", title: "Retention", body: <><p>Account data is kept while your account is active and for 90 days after deletion to handle disputes, then removed or anonymised. Invoices, escrow records and work orders are kept for 8 years to meet Indian tax and accounting rules. Verification documents are deleted 12 months after a decision. Audit logs are kept for 2 years. Anonymous feedback responses are retained indefinitely in aggregate.</p></> },
        { id: "rights", title: "Your rights and choices", body: <><ul><li><strong>Access and export:</strong> download your data any time from Settings (CSV and JSON).</li><li><strong>Correction:</strong> edit your profile and company details in Settings.</li><li><strong>Deletion:</strong> request account deletion from Settings or by email. Some records must be retained as described above.</li><li><strong>Consent:</strong> withdraw marketing, WhatsApp/SMS or push consent in Settings at any time.</li><li><strong>Grievance:</strong> write to our grievance officer at <a href="mailto:hello@corpgurus.com" className="text-cyan hover:underline">hello@corpgurus.com</a>. We respond within 15 days. You may also approach the Data Protection Board of India.</li></ul></> },
        { id: "cookies", title: "Cookies and local storage", body: <><p>We use a session cookie to keep you signed in, a language cookie, and local storage for dismissed banners, saved drafts and offline support. We do not use third-party advertising cookies. Payment providers may set their own cookies on their checkout pages.</p></> },
        { id: "security", title: "Security", body: <><p>Passwords are hashed with bcrypt; sessions are signed tokens in HTTP-only cookies; connections use HTTPS; API keys and webhook secrets are stored hashed or encrypted; verification documents are served only to staff; staff actions on member accounts are logged and shown to the member. No system is perfectly secure, so please use a strong, unique password.</p></> },
        { id: "children", title: "Children", body: <><p>The Platform is for professionals aged 18 and over. We do not knowingly collect data from children.</p></> },
        { id: "transfers", title: "International transfers", body: <><p>Some providers process data outside India (for example, email delivery). We choose providers with adequate safeguards and contractual protections. USD billing through Stripe involves data processing in the United States.</p></> },
        { id: "changes", title: "Changes", body: <><p>We will post updates here and notify you by email of material changes at least 14 days before they take effect.</p></> },
      ]}
    />
  );
}
