import { LegalPage } from "@/components/legal";
import { pageMeta } from "@/lib/seo";

export const metadata = pageMeta({ title: "Refunds and cancellations", description: "CorpGurus refund and cancellation policy for subscriptions, escrow deposits and training engagements booked through work orders.", path: "/legal/refunds" });

export default function RefundsPage() {
  return (
    <LegalPage title="Refunds & cancellations" effective="1 October 2026" current="refunds"
      intro={<p>This policy covers three kinds of money on CorpGurus: subscription fees paid to CorpGurus, escrow deposits held by CorpGurus on a company’s behalf, and payments between a company and a trainer under a work order. Where a work order states its own cancellation terms, those terms win.</p>}
      sections={[
        { id: "subscriptions", title: "Subscriptions (Trainer Pro, Company Growth, Training Partner)", body: <><ul><li>Cancel any time from Settings → Plan &amp; billing. Access continues until the end of the period already paid; the plan then returns to free.</li><li><strong>First 7 days:</strong> if you cancel within 7 days of your first payment on a plan and have not used a paid-only feature (unlimited applications, unlimited requirements, direct messaging, API keys), we refund that payment in full on request.</li><li><strong>After 7 days</strong> there are no pro-rated refunds for unused time on monthly or yearly plans.</li><li><strong>Duplicate or erroneous charges</strong> are refunded in full. Write to <a href="mailto:hello@corpgurus.com" className="text-cyan hover:underline">hello@corpgurus.com</a> with the payment reference.</li><li>Refunds go back to the original payment method through Razorpay or Stripe and typically appear within 5 to 10 working days.</li></ul></> },
        { id: "escrow", title: "Escrow deposits", body: <><ul><li>A deposit is refundable in full while it is <strong>funded and not yet released</strong> and the work order has been cancelled by the company, or when both parties ask CorpGurus in writing to refund it. The platform fee is not charged on refunded deposits.</li><li>Once the company <strong>releases</strong> a deposit it is paid out to the trainer and cannot be refunded by CorpGurus. Any dispute after release is between the company and the trainer.</li><li>If a company cancels a funded engagement inside the notice period stated in the work order (or inside 7 days of the start date when the work order is silent), the trainer may claim the cancellation amount from the deposit. CorpGurus releases the claimed part to the trainer and refunds the rest after both parties confirm, or after 14 days if the company does not respond.</li><li>Payment-gateway charges on refunds are borne by CorpGurus for cancellations initiated by the trainer, and by the company otherwise.</li></ul></> },
        { id: "engagements", title: "Training engagements (direct payment)", body: <><p>When a company pays the trainer directly, refunds and cancellation charges follow the work order. If the work order is silent, the default is:</p><ul><li>Reschedule free of charge up to 7 days before the start date.</li><li>Cancellation within 7 days of the start date: 50% of the work-order total payable to the trainer.</li><li>Cancellation on or after the start date, or no-show by the participants: 100% payable.</li><li>Trainer cancellation: no fee payable by the company; CorpGurus may record the cancellation on the trainer’s profile.</li></ul></> },
        { id: "how", title: "How to request a refund", body: <><p>Email <a href="mailto:hello@corpgurus.com" className="text-cyan hover:underline">hello@corpgurus.com</a> from your account email with the plan or work-order number and the reason. We acknowledge within 2 working days and decide within 7. Approved refunds are processed to the original payment method.</p></> },
      ]}
    />
  );
}
