import "dotenv/config";
import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

interface CompanyData {
  name: string;
  slug: string;
  domain: string;
  description: string;
  interviewTypes: string[];
  questions: {
    category: string;
    difficulty: string;
    question: string;
    sampleAnswer: string;
    tips: string;
    tags: string[];
  }[];
}

const companies: CompanyData[] = [
  {
    name: "Tata Consultancy Services",
    slug: "tcs",
    domain: "IT Services",
    description: "India's largest IT services company. Known for mass hiring of freshers with strong focus on aptitude, coding, and communication skills.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL"],
    questions: [
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the difference between an array and a linked list?", sampleAnswer: "Arrays store elements in contiguous memory locations with O(1) random access but O(n) insertion/deletion. Linked lists store elements with pointers to next nodes, offering O(1) insertion/deletion at known positions but O(n) access time.", tips: "Draw diagrams to explain memory layout. Mention when you'd pick one over the other.", tags: ["DSA", "Data Structures"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "Explain the concept of OOPS with real-world examples.", sampleAnswer: "OOP has 4 pillars: Encapsulation (ATM hides internal logic), Inheritance (child class gets parent properties like Dog extends Animal), Polymorphism (same method behaves differently — overloading/overriding), Abstraction (car steering wheel hides engine complexity).", tips: "TCS loves real-world analogies. Prepare 2 examples for each OOP concept.", tags: ["OOP", "Java", "Core CS"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is normalization in databases? Explain up to 3NF.", sampleAnswer: "Normalization reduces data redundancy. 1NF: atomic values, no repeating groups. 2NF: 1NF + no partial dependencies (every non-key column depends on full primary key). 3NF: 2NF + no transitive dependencies (non-key columns depend only on primary key, not other non-key columns).", tips: "Use a simple student-course table example to walk through each normal form.", tags: ["DBMS", "SQL"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Write a program to check if a string is a palindrome.", sampleAnswer: "Compare the string with its reverse. In Python: `return s == s[::-1]`. For case-insensitive: clean the string first with `s.lower().replace(' ', '')`. Alternatively, use two pointers from both ends moving inward.", tips: "Mention edge cases: empty string, single character, strings with spaces. Show both iterative and Pythonic approaches.", tags: ["Coding", "Strings"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Explain TCP vs UDP with use cases.", sampleAnswer: "TCP is connection-oriented, reliable (guaranteed delivery, ordering), slower — used for web browsing, email, file transfer. UDP is connectionless, unreliable but faster — used for video streaming, gaming, DNS queries, VoIP.", tips: "Mention the 3-way handshake for TCP. TCS often follows up with 'which would you use for a chat app?'", tags: ["Networking", "Protocols"] },
      { category: "HR", difficulty: "EASY", question: "Tell me about yourself.", sampleAnswer: "Structure: Present (current education/role) → Past (relevant experience/projects) → Future (career goals aligned with TCS). Example: 'I'm a final year B.Tech student at [college] specializing in [field]. During college, I built [project] and interned at [company]. I'm looking to start my career at TCS because of its global exposure and learning opportunities.'", tips: "Keep it under 2 minutes. Don't recite your resume. End with why you want to join TCS specifically.", tags: ["Self Introduction"] },
      { category: "HR", difficulty: "EASY", question: "Why do you want to join TCS?", sampleAnswer: "TCS offers structured learning paths for freshers, global project exposure across domains (BFSI, healthcare, retail), and a strong culture of innovation with TCS Pace and research labs. The Initial Learning Program (ILP) is one of the best in the industry for building a strong foundation.", tips: "Research TCS ILP, TCS Pace, and recent TCS news. Mention specific programs or initiatives.", tags: ["Company Knowledge"] },
      { category: "HR", difficulty: "MEDIUM", question: "Are you comfortable with relocation? What if you're posted to a city you don't prefer?", sampleAnswer: "Yes, I'm open to relocation. I see it as an opportunity to experience different cultures and grow professionally. I believe adaptability is key in the IT industry, and I'm prepared to move wherever the project needs me.", tips: "TCS always asks this. Never say no. They need flexibility for client projects across India and abroad.", tags: ["Relocation", "Flexibility"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "Describe a situation where you worked in a team.", sampleAnswer: "Use STAR method. Situation: College hackathon with 4-member team. Task: Build a web app in 24 hours. Action: I took ownership of the backend, coordinated with the frontend developer, resolved a merge conflict at 3 AM. Result: We won second place and I learned the value of clear communication under pressure.", tips: "Use STAR format always. Pick a specific incident, not a generic answer.", tags: ["Teamwork", "STAR"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Tell me about a time you failed and what you learned.", sampleAnswer: "STAR: In my 3rd semester, I led a project but didn't delegate well — I tried doing everything myself. The project was late and incomplete. I learned that leadership means trusting your team. In the next project, I assigned tasks based on strengths, held daily standups, and we delivered on time.", tips: "Genuine failures are impressive when paired with genuine lessons. Don't pick a fake weakness.", tags: ["Failure", "Growth"] },
      { category: "TECHNICAL", difficulty: "HARD", question: "Explain the differences between process and thread. When would you use multithreading?", sampleAnswer: "A process is an independent program with its own memory space. A thread is a lightweight unit within a process sharing the same memory. Multithreading is useful for I/O-bound tasks (web servers handling multiple requests), parallel computation, and responsive UIs. Challenges include race conditions and deadlocks.", tips: "Mention practical examples. Follow up with knowledge of synchronization mechanisms (mutex, semaphore).", tags: ["OS", "Concurrency"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the difference between SQL and NoSQL databases?", sampleAnswer: "SQL databases are relational, use structured schemas, support ACID transactions (MySQL, PostgreSQL). NoSQL databases are non-relational, schema-flexible, optimized for horizontal scaling (MongoDB, Cassandra). Choose SQL for complex queries and data integrity; NoSQL for large-scale, rapidly changing data.", tips: "Give examples of when you'd pick each. Mention CAP theorem if you know it.", tags: ["DBMS", "SQL", "NoSQL"] },
    ],
  },
  {
    name: "Infosys",
    slug: "infosys",
    domain: "IT Services",
    description: "Global leader in digital services and consulting. Infosys hires freshers through InfyTQ platform and focuses on logical reasoning, coding, and communication.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL"],
    questions: [
      { category: "TECHNICAL", difficulty: "EASY", question: "What are the different types of joins in SQL?", sampleAnswer: "INNER JOIN: returns matching rows from both tables. LEFT JOIN: all rows from left + matching from right. RIGHT JOIN: all rows from right + matching from left. FULL OUTER JOIN: all rows from both tables. CROSS JOIN: cartesian product of both tables.", tips: "Draw Venn diagrams. Infosys often asks you to write a query using joins.", tags: ["SQL", "DBMS"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the difference between stack and queue?", sampleAnswer: "Stack follows LIFO (Last In First Out) — like a stack of plates. Operations: push, pop, peek. Queue follows FIFO (First In First Out) — like a line at a counter. Operations: enqueue, dequeue, front. Stack uses: undo operations, expression evaluation. Queue uses: BFS, task scheduling.", tips: "Mention real-world analogies and at least 2 use cases for each.", tags: ["DSA", "Data Structures"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Explain the concept of virtual memory.", sampleAnswer: "Virtual memory allows programs to use more memory than physically available by swapping data between RAM and disk. The OS uses page tables to map virtual addresses to physical addresses. Pages not in RAM are stored on disk (page file). When accessed, a page fault occurs and the OS loads the needed page.", tips: "Mention page replacement algorithms (LRU, FIFO) as a follow-up knowledge point.", tags: ["OS", "Memory Management"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Write a program to find the second largest element in an array.", sampleAnswer: "Initialize two variables: largest = arr[0], secondLargest = -infinity. Traverse the array: if element > largest, secondLargest = largest, largest = element. Else if element > secondLargest and element != largest, secondLargest = element. Time: O(n), Space: O(1).", tips: "Don't sort the array (O(n log n)). Show the single-pass O(n) approach. Handle edge cases: array with all same elements.", tags: ["Coding", "Arrays"] },
      { category: "HR", difficulty: "EASY", question: "Why Infosys over other IT companies?", sampleAnswer: "Infosys is a pioneer in employee development with platforms like Lex and InfyTQ. The Infosys Foundation's work in education and sustainability aligns with my values. Infosys Springboard offers 10 million learners free skilling — showing commitment beyond just business. The flat hierarchy and innovation culture at Infosys Innovation Network make it ideal for freshers.", tips: "Reference Infosys Springboard, InfyTQ, and recent news. Don't badmouth competitors.", tags: ["Company Knowledge"] },
      { category: "HR", difficulty: "MEDIUM", question: "Where do you see yourself in 5 years?", sampleAnswer: "In 5 years, I see myself as a technical lead or solution architect at Infosys, having developed deep expertise in [cloud/data/security]. I want to contribute to large-scale digital transformation projects and mentor junior developers. I'm also interested in pursuing relevant certifications to grow.", tips: "Be realistic — don't say CEO. Show ambition within the company. Mention specific Infosys career paths if you know them.", tags: ["Career Goals"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "How do you handle pressure and tight deadlines?", sampleAnswer: "I prioritize tasks using urgency and impact, break large tasks into smaller milestones, and communicate proactively with the team if timelines are at risk. During my final year project, we had a 2-week deadline pushed to 1 week. I created a daily checklist, worked in focused sprints, and we delivered on time.", tips: "Give a specific example. Show you stay organized, not just 'I work harder'.", tags: ["Pressure", "Time Management"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Describe a conflict you had with a team member and how you resolved it.", sampleAnswer: "In a group project, a teammate consistently missed deadlines, affecting everyone. Instead of complaining, I had a private conversation, understood they were struggling with the tech stack. I paired with them for 2 sessions to help. They caught up, and we delivered a strong project. I learned that addressing issues directly but empathetically works best.", tips: "Show empathy and problem-solving. Never blame the other person entirely.", tags: ["Conflict Resolution", "STAR"] },
      { category: "TECHNICAL", difficulty: "HARD", question: "Explain the ACID properties of a database transaction.", sampleAnswer: "Atomicity: transaction is all-or-nothing. Consistency: DB moves from one valid state to another. Isolation: concurrent transactions don't interfere. Durability: committed data survives crashes. Example: bank transfer — debit and credit must both succeed (atomic), balance must remain valid (consistent), parallel transfers don't conflict (isolated), and after commit, it persists (durable).", tips: "Use the bank transfer example — interviewers love it. Mention isolation levels if asked to go deeper.", tags: ["DBMS", "Transactions"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is an API? Explain REST API.", sampleAnswer: "API (Application Programming Interface) lets two software systems communicate. REST API follows principles: client-server architecture, statelessness, uniform interface (HTTP methods: GET, POST, PUT, DELETE), resource-based URLs. Example: GET /api/users returns user list, POST /api/users creates a new user.", tips: "Mention HTTP status codes (200, 201, 404, 500) and JSON format. Very common Infosys question.", tags: ["Web", "API"] },
    ],
  },
  {
    name: "Wipro",
    slug: "wipro",
    domain: "IT Services",
    description: "One of India's top IT companies with global presence. Wipro's interview process includes aptitude tests, technical rounds, and HR discussions.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL"],
    questions: [
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the difference between Java and JavaScript?", sampleAnswer: "Java is a compiled, statically-typed, class-based OOP language used for enterprise applications, Android apps, and backend. JavaScript is an interpreted, dynamically-typed, prototype-based language primarily for web development (frontend + Node.js backend). Despite similar names, they have completely different type systems, execution environments, and use cases.", tips: "This catches many freshers off guard. Be clear about the fundamental differences.", tags: ["Java", "JavaScript", "Programming Languages"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "Explain what a primary key and foreign key are.", sampleAnswer: "Primary key uniquely identifies each row in a table — cannot be null or duplicate. Foreign key is a column in one table that references the primary key of another table, establishing a relationship between tables. Example: In an Orders table, order_id is the primary key, and customer_id is a foreign key referencing the Customers table.", tips: "Always give a relational example with 2 tables. Mention referential integrity.", tags: ["DBMS", "SQL"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "What is the difference between abstract class and interface?", sampleAnswer: "Abstract class can have both abstract and concrete methods, supports constructors, and allows any access modifier. Interface (pre-Java 8) only has abstract methods with public access. A class can implement multiple interfaces but extend only one abstract class. Use abstract class for 'is-a' with shared code; interface for 'can-do' capabilities.", tips: "Mention Java 8+ default methods in interfaces. Give a practical example: Vehicle abstract class vs Drivable interface.", tags: ["OOP", "Java"] },
      { category: "HR", difficulty: "EASY", question: "What do you know about Wipro?", sampleAnswer: "Wipro is a leading global IT services company founded by Azim Premji, headquartered in Bangalore. It offers IT consulting, system integration, and digital transformation services across 66+ countries. Recent focus areas include cloud (partnership with major cloud providers), AI/ML services, and cybersecurity. Wipro's LEAD program is excellent for fresher development.", tips: "Mention Wipro's sustainability initiatives and Azim Premji Foundation. Shows you've done research.", tags: ["Company Knowledge"] },
      { category: "HR", difficulty: "MEDIUM", question: "What is your biggest weakness?", sampleAnswer: "I sometimes spend too much time perfecting my code before moving to the next task. I've been working on this by setting time limits for each task and following the 80/20 rule — get it working first, then optimize. This has improved my delivery speed without sacrificing quality.", tips: "Pick a genuine weakness but show you're actively working on it. Never say 'I'm a perfectionist' without context.", tags: ["Self-Awareness"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "Tell me about a project you're proud of.", sampleAnswer: "STAR: In my final year, I built a real-time attendance system using face recognition (Python, OpenCV, Flask). The challenge was accuracy in varying light conditions. I implemented histogram equalization and trained the model on augmented data. Result: 95% accuracy, deployed in our department, saving 15 minutes per class.", tips: "Pick a project that shows technical depth and real impact. Quantify results.", tags: ["Projects", "STAR"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "What is deadlock? How can it be prevented?", sampleAnswer: "Deadlock occurs when two or more processes are waiting for each other to release resources, creating a circular wait. Four conditions: mutual exclusion, hold and wait, no preemption, circular wait. Prevention: break any one condition — e.g., request all resources at once (prevent hold-and-wait), or use resource ordering (prevent circular wait).", tips: "Draw the circular wait diagram. Mention Banker's algorithm for deadlock avoidance if asked.", tags: ["OS", "Concurrency"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "How do you handle criticism?", sampleAnswer: "I view criticism as an opportunity to improve. In my internship, my manager pointed out my code lacked proper error handling. Instead of getting defensive, I asked for examples of good error handling, studied the codebase, and within a week, my code quality improved significantly. My manager later appreciated the quick turnaround.", tips: "Show maturity and willingness to learn. Never say you don't receive criticism.", tags: ["Growth Mindset", "STAR"] },
    ],
  },
  {
    name: "Google",
    slug: "google",
    domain: "Technology",
    description: "World's leading tech company. Google's interview process is highly structured with focus on data structures, algorithms, system design, and Googleyness.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Given an array of integers, find two numbers that add up to a specific target.", sampleAnswer: "Use a hash map. Iterate through the array: for each number, check if (target - number) exists in the map. If yes, return both indices. If no, add current number to map. Time: O(n), Space: O(n). This is the classic Two Sum problem.", tips: "Start with brute force O(n²), then optimize to hash map O(n). Discuss edge cases: empty array, no solution, duplicates.", tags: ["DSA", "Arrays", "Hash Map", "LeetCode"] },
      { category: "TECHNICAL", difficulty: "HARD", question: "Design a function to detect a cycle in a linked list.", sampleAnswer: "Floyd's Cycle Detection (tortoise and hare): Use two pointers, slow (moves 1 step) and fast (moves 2 steps). If there's a cycle, they'll meet. If fast reaches null, no cycle. Time: O(n), Space: O(1). To find cycle start: after meeting, reset one pointer to head, move both 1 step at a time — they meet at cycle start.", tips: "Explain why Floyd's works mathematically if asked. Mention the O(n) space hash set approach first, then optimize.", tags: ["DSA", "Linked List", "Two Pointers"] },
      { category: "TECHNICAL", difficulty: "HARD", question: "Explain how a hash map works internally. What happens during a collision?", sampleAnswer: "Hash map stores key-value pairs using a hash function to compute bucket index. Collisions occur when different keys map to the same bucket. Resolution strategies: chaining (linked list at each bucket) or open addressing (linear probing, quadratic probing, double hashing). Load factor determines when to resize. Average operations: O(1), worst case: O(n).", tips: "Google expects you to understand internals, not just API usage. Discuss amortized complexity of rehashing.", tags: ["DSA", "Hash Map", "Core CS"] },
      { category: "SYSTEM_DESIGN", difficulty: "MEDIUM", question: "Design a URL shortener like bit.ly.", sampleAnswer: "Requirements: shorten URL, redirect, analytics. Architecture: Web server → Application layer → Database. Key decisions: generate unique short code (base62 encoding of auto-increment ID or random), store mapping in database (short_code → original_url), 301 redirect for cached or 302 for analytics. Scale: cache popular URLs in Redis, use consistent hashing for DB sharding.", tips: "Start with requirements clarification. Discuss trade-offs: base62 vs random, SQL vs NoSQL, caching strategies.", tags: ["System Design", "Scalability"] },
      { category: "SYSTEM_DESIGN", difficulty: "HARD", question: "Design a notification system that handles millions of users.", sampleAnswer: "Components: API gateway, notification service, message queues (Kafka), delivery services (push, email, SMS), user preference store, rate limiter, analytics. Flow: event triggers notification → service checks user preferences → enqueues to appropriate channel queue → delivery service sends. Key considerations: priority queues, retry with exponential backoff, deduplication, template engine.", tips: "Discuss reliability, scalability, and user experience. Mention fan-out patterns and priority handling.", tags: ["System Design", "Distributed Systems"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Tell me about a time you had to make a decision with incomplete information.", sampleAnswer: "During a hackathon, we had to choose between React and Vue for the frontend with 30 minutes left to decide. I didn't have time to benchmark both, so I assessed team familiarity (3/4 knew React), project requirements (needed rich ecosystem), and community support. We went with React and finished on time. The decision was right — but I also identified what I'd investigate next time.", tips: "Google calls this 'Googleyness.' Show intellectual humility and structured thinking even under uncertainty.", tags: ["Decision Making", "Googleyness"] },
      { category: "HR", difficulty: "EASY", question: "Why Google?", sampleAnswer: "Google's engineering culture — the emphasis on solving problems at scale, the 20% time for innovation, and the open collaboration across teams — aligns with how I work best. I'm particularly drawn to [specific product/area] because of its impact on [specific user benefit]. The opportunity to learn from world-class engineers while contributing to products used by billions is unmatched.", tips: "Be specific about which Google product or team interests you. Generic answers like 'Google is innovative' won't work.", tags: ["Company Knowledge"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "What is the time complexity of common sorting algorithms?", sampleAnswer: "Bubble/Selection/Insertion: O(n²) average and worst. Merge Sort: O(n log n) always (stable, extra space). Quick Sort: O(n log n) average, O(n²) worst (in-place, not stable). Heap Sort: O(n log n) always (in-place, not stable). Counting/Radix: O(n+k) for bounded integers. Python's Timsort: O(n log n), hybrid of merge+insertion.", tips: "Know when to use which. Google often asks 'which sort would you use for nearly sorted data?' (Insertion sort — O(n)).", tags: ["DSA", "Sorting", "Complexity"] },
    ],
  },
  {
    name: "Amazon",
    slug: "amazon",
    domain: "Technology",
    description: "E-commerce and cloud computing giant. Amazon interviews focus heavily on Leadership Principles, coding, and system design.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "How would you find the longest substring without repeating characters?", sampleAnswer: "Sliding window approach: use two pointers (left, right) and a hash set. Expand right pointer, adding characters to set. If duplicate found, shrink from left until no duplicate. Track max length. Time: O(n), Space: O(min(n, alphabet size)).", tips: "This is a classic Amazon question. Walk through an example string step by step. Mention the hash map optimization for direct left pointer jumps.", tags: ["DSA", "Sliding Window", "Strings"] },
      { category: "TECHNICAL", difficulty: "HARD", question: "Design an LRU (Least Recently Used) cache.", sampleAnswer: "Combine a hash map (O(1) lookup) with a doubly linked list (O(1) insertion/deletion). Hash map stores key → node pointer. On get: move node to front. On put: add to front, if capacity exceeded, remove from tail. Both operations are O(1).", tips: "This is asked very frequently. Implement it from scratch. Discuss thread safety as a follow-up.", tags: ["DSA", "Design", "Hash Map", "Linked List"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Tell me about a time you disagreed with your manager or team lead. (Leadership Principle: Have Backbone, Disagree and Commit)", sampleAnswer: "STAR: In my internship, my lead wanted to use a monolithic approach for a microservice project. I believed microservices were better for our scaling needs. I presented a comparison with pros/cons, load projections, and deployment complexity. After discussion, the team agreed on microservices. Even if they hadn't, I would have committed fully to the team's decision.", tips: "Amazon maps every behavioral question to a Leadership Principle. Research all 16 LPs. Show data-backed disagreement, not emotional conflict.", tags: ["Leadership Principles", "STAR"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Give me an example of when you took ownership of a problem. (Leadership Principle: Ownership)", sampleAnswer: "During a group project, our deployment was failing and the DevOps person was unavailable. Instead of waiting, I spent the weekend learning Docker and CI/CD, debugged the pipeline, and got the deployment working. I also documented the process so the team wouldn't face the same issue. I believe in not saying 'that's not my job.'", tips: "Ownership is Amazon's most important LP. Show you go beyond your defined role.", tags: ["Leadership Principles", "STAR", "Ownership"] },
      { category: "SYSTEM_DESIGN", difficulty: "MEDIUM", question: "Design an e-commerce order processing system.", sampleAnswer: "Components: Order Service, Inventory Service, Payment Service, Notification Service, all communicating via message queues (SQS/Kafka). Flow: User places order → Order Service validates → Inventory Service reserves stock → Payment Service charges → on success, confirm order and notify. Use saga pattern for distributed transactions. Consider: idempotency, retry logic, dead letter queues.", tips: "Amazon loves this — it's their core business. Discuss eventual consistency, compensating transactions, and failure handling.", tags: ["System Design", "E-commerce"] },
      { category: "HR", difficulty: "EASY", question: "Why Amazon?", sampleAnswer: "Amazon's customer obsession resonates with me — every technical decision starts with the customer. The scale of problems Amazon solves (millions of orders, AWS serving 33% of cloud) means I'll learn to build systems that matter. The Leadership Principles, especially 'Bias for Action' and 'Learn and Be Curious,' describe how I naturally work.", tips: "Reference specific Leadership Principles. Amazon's interview is 80% LP-based.", tags: ["Company Knowledge", "Leadership Principles"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the difference between DFS and BFS?", sampleAnswer: "DFS (Depth-First Search) explores as deep as possible before backtracking. Uses stack (or recursion). Good for: path finding, topological sort, detecting cycles. BFS (Breadth-First Search) explores neighbors level by level. Uses queue. Good for: shortest path in unweighted graphs, level-order traversal. DFS Space: O(h), BFS Space: O(w) where h=height, w=max width.", tips: "Know both iterative and recursive implementations. Common follow-up: 'When would BFS be better than DFS?'", tags: ["DSA", "Graphs", "Trees"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "Tell me about a time you delivered a project under a tight deadline. (Leadership Principle: Deliver Results)", sampleAnswer: "STAR: My college project deadline was moved up by 2 weeks due to exam schedule changes. I created a priority matrix, identified must-have vs nice-to-have features, focused the team on the MVP, and we delivered a working product 1 day early. We later added remaining features. I learned that shipping something good on time beats shipping something perfect late.", tips: "Amazon values 'Bias for Action.' Show pragmatic decision-making, not just hard work.", tags: ["Leadership Principles", "STAR", "Delivery"] },
    ],
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    domain: "Technology",
    description: "Technology leader in cloud, productivity, and AI. Microsoft interviews focus on coding, problem-solving, system design, and growth mindset.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Reverse a linked list iteratively and recursively.", sampleAnswer: "Iterative: use 3 pointers (prev=null, curr=head, next). While curr exists: next=curr.next, curr.next=prev, prev=curr, curr=next. Return prev. Recursive: base case: head is null or head.next is null. Recursive: rest = reverse(head.next), head.next.next = head, head.next = null. Return rest.", tips: "Microsoft expects clean code with both approaches. Discuss time O(n) and space (O(1) iterative, O(n) recursive stack).", tags: ["DSA", "Linked List"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Explain the difference between HTTP and HTTPS.", sampleAnswer: "HTTP sends data in plaintext — anyone intercepting can read it. HTTPS uses TLS/SSL encryption to secure the connection. Process: client sends hello, server responds with certificate, client verifies certificate, symmetric key exchange, encrypted communication begins. HTTPS prevents man-in-the-middle attacks, data tampering, and eavesdropping.", tips: "Mention the TLS handshake steps. Microsoft cares about security fundamentals.", tags: ["Networking", "Security", "Web"] },
      { category: "SYSTEM_DESIGN", difficulty: "MEDIUM", question: "Design a real-time collaborative document editor like Google Docs.", sampleAnswer: "Key challenge: conflict resolution when multiple users edit simultaneously. Approaches: OT (Operational Transformation) or CRDT (Conflict-free Replicated Data Types). Architecture: WebSocket server for real-time sync, document store, operation log, presence service (who's editing where). Use cursor position tracking, change deltas, and version vectors.", tips: "Microsoft builds this (Office 365). Focus on conflict resolution strategy and user experience.", tags: ["System Design", "Real-time", "Collaboration"] },
      { category: "HR", difficulty: "EASY", question: "What Microsoft product inspires you and why?", sampleAnswer: "GitHub Copilot fascinates me — it represents the intersection of AI and developer productivity. The way it uses LLMs trained on code to provide contextual suggestions is transforming how developers work. I've used it myself and seen 30% faster development on repetitive tasks. It shows Microsoft's vision of AI augmenting human capabilities, not replacing them.", tips: "Pick a product you've actually used. Mention specific features and impact. Azure, VS Code, Teams, Copilot are good choices.", tags: ["Company Knowledge", "Product Sense"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Tell me about a time you learned something new quickly to solve a problem.", sampleAnswer: "STAR: My team needed to implement real-time notifications but none of us knew WebSockets. I spent 2 days learning Socket.io through docs and tutorials, built a proof of concept, and presented it to the team. We implemented it in our project within a week. I documented the learnings in a wiki for future reference.", tips: "Microsoft values 'Growth Mindset.' Show curiosity, speed of learning, and knowledge sharing.", tags: ["Growth Mindset", "Learning", "STAR"] },
      { category: "TECHNICAL", difficulty: "HARD", question: "Implement a trie (prefix tree) and explain its use cases.", sampleAnswer: "Trie is a tree where each node represents a character. Operations: insert (traverse/create nodes for each char), search (traverse, check end marker), startsWith (traverse, return true if path exists). Time: O(m) for all operations where m = word length. Use cases: autocomplete, spell checker, IP routing, dictionary.", tips: "Write clean insert and search methods. Mention space optimization with compressed tries.", tags: ["DSA", "Trees", "Advanced"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "How do you stay updated with technology?", sampleAnswer: "I follow a structured approach: daily tech newsletters (TLDR, Morning Brew Tech), weekly YouTube channels (Fireship, Traversy Media), monthly deep-dives on specific topics through documentation and courses. I also contribute to open source on GitHub and participate in hackathons to apply new technologies hands-on.", tips: "Be specific about sources. Mention a recent tech trend you're excited about.", tags: ["Learning", "Self-Development"] },
    ],
  },
  {
    name: "Flipkart",
    slug: "flipkart",
    domain: "E-commerce",
    description: "India's largest e-commerce platform (Walmart-owned). Interviews focus on DSA, system design, and problem-solving with Indian market context.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "How would you implement a search autocomplete feature?", sampleAnswer: "Use a Trie data structure for prefix matching. On each keystroke, traverse the trie to the prefix node, then DFS to collect all words with that prefix. Optimize with: frequency-based ranking (most popular suggestions first), caching top-K results for common prefixes, debouncing keystrokes (300ms), and a separate indexing service for updates.", tips: "Flipkart's search is critical to their business. Mention relevance ranking and personalization as bonus points.", tags: ["DSA", "Trie", "System Design"] },
      { category: "TECHNICAL", difficulty: "HARD", question: "Design a rate limiter.", sampleAnswer: "Algorithms: Token Bucket (smooth rate, allows bursts), Sliding Window (accurate but more memory), Fixed Window Counter (simple but boundary issues). Implementation: Redis for distributed state, middleware/decorator pattern. Key decisions: rate limit by user ID, IP, or API key. Handle: exceeded limit (429 status), headers (X-RateLimit-Remaining), distributed clock sync.", tips: "Discuss trade-offs between algorithms. Flipkart needs this for flash sales. Mention their Big Billion Days scale.", tags: ["System Design", "Algorithms"] },
      { category: "SYSTEM_DESIGN", difficulty: "HARD", question: "Design Flipkart's cart and checkout system for Big Billion Days sale.", sampleAnswer: "Challenges: millions of concurrent users, inventory race conditions. Architecture: Cart service (Redis for speed), Inventory service (optimistic locking), Queue-based checkout (prevent thundering herd), Payment gateway with retry. Key patterns: reservation system (hold inventory for 10 min), eventual consistency, circuit breakers, surge pricing. CDN for static assets, auto-scaling.", tips: "This is Flipkart's biggest challenge. Focus on handling 10x normal traffic. Mention inventory reservation vs real-time stock check trade-off.", tags: ["System Design", "E-commerce", "Scale"] },
      { category: "HR", difficulty: "EASY", question: "Why Flipkart?", sampleAnswer: "Flipkart is solving uniquely Indian problems — COD in a cash-heavy economy, last-mile delivery to tier-2/3 cities, vernacular shopping experiences. The engineering scale (100M+ users, BBD traffic spikes) offers challenges I can't find elsewhere. Being Walmart-backed gives global exposure while solving local problems.", tips: "Show knowledge of India-specific challenges Flipkart solves. Mention recent innovations like voice commerce or super coins.", tags: ["Company Knowledge"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Tell me about a time you optimized something.", sampleAnswer: "STAR: Our college website's page load was 8 seconds. I profiled it — found unoptimized images (60% of load time) and blocking JavaScript. I implemented lazy loading, WebP conversion, code splitting, and Redis caching for API responses. Result: load time dropped to 1.8 seconds, bounce rate decreased by 40%.", tips: "Quantify the improvement. Show the before/after with metrics. Flipkart cares deeply about performance.", tags: ["Optimization", "STAR", "Performance"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the difference between GET and POST HTTP methods?", sampleAnswer: "GET retrieves data, is idempotent, parameters in URL (visible, limited length), cacheable, bookmarkable. POST submits data, is not idempotent, parameters in request body (hidden, no size limit), not cacheable. Use GET for reading data, POST for creating/modifying. Other methods: PUT (update), DELETE (remove), PATCH (partial update).", tips: "Mention idempotency — it's a key concept. Follow up with PUT vs PATCH difference.", tags: ["Web", "HTTP", "API"] },
    ],
  },
  {
    name: "Razorpay",
    slug: "razorpay",
    domain: "Fintech",
    description: "India's leading payment gateway. Razorpay interviews focus on system design, coding, and fintech domain knowledge.",
    interviewTypes: ["TECHNICAL", "HR", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "How would you ensure data consistency in a payment system?", sampleAnswer: "Use ACID transactions for critical operations. Implement idempotency keys to prevent double charges. Use saga pattern for distributed transactions (payment → inventory → notification). Implement reconciliation jobs to detect inconsistencies. Use event sourcing to maintain audit trail. Two-phase commit for cross-service consistency.", tips: "Fintech requires zero tolerance for inconsistency. Mention PCI DSS compliance and data encryption at rest and in transit.", tags: ["System Design", "Payments", "Consistency"] },
      { category: "SYSTEM_DESIGN", difficulty: "HARD", question: "Design a payment gateway that processes 1000 transactions per second.", sampleAnswer: "Architecture: Load balancer → API gateway (rate limiting, auth) → Payment orchestrator → Bank/card network adapters. Key: async processing with message queues, idempotency, circuit breakers for failing banks, retry with exponential backoff, webhook delivery for status updates. Database: PostgreSQL for transactions (ACID), Redis for caching/sessions. Monitoring: real-time fraud detection, latency tracking.", tips: "Razorpay processes millions daily. Focus on reliability, idempotency, and failure handling. Mention PCI DSS.", tags: ["System Design", "Fintech", "Scale"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Explain eventual consistency and where it's appropriate.", sampleAnswer: "Eventual consistency means all replicas will converge to the same state given enough time without new updates. It trades immediate consistency for availability and performance (CAP theorem). Appropriate for: notification counts, analytics dashboards, search indices, social media feeds. Not appropriate for: bank balances, inventory counts during checkout, authentication.", tips: "Mention the CAP theorem. Give both good and bad use cases for eventual consistency.", tags: ["Distributed Systems", "CAP Theorem"] },
      { category: "HR", difficulty: "EASY", question: "Why fintech? Why Razorpay?", sampleAnswer: "India's digital payments revolution (UPI crossing 10B monthly transactions) is the most exciting engineering space right now. Razorpay powers 8M+ businesses — from street vendors to enterprises. I'm drawn to the combination of scale, reliability requirements, and direct impact on India's economy. Building systems where even 0.01% failure affects thousands of transactions is the kind of challenge I want.", tips: "Show knowledge of UPI, India's digital payments landscape, and Razorpay's product suite (Payment Gateway, RazorpayX, Payroll).", tags: ["Company Knowledge", "Fintech"] },
      { category: "TECHNICAL", difficulty: "HARD", question: "How would you implement a fraud detection system?", sampleAnswer: "Layers: Rule-based (velocity checks, amount thresholds, geo-anomalies) → ML-based (classification model trained on historical fraud data — features: transaction amount, time, device, location, merchant category). Real-time scoring via a feature store. Suspicious transactions → queue for manual review. Implement: shadow mode (score without blocking) before full deployment. Continuous model retraining.", tips: "Combine rules and ML. Mention false positive rates and their business impact. Razorpay deals with this daily.", tags: ["ML", "Fraud Detection", "Fintech"] },
    ],
  },
  {
    name: "Zomato",
    slug: "zomato",
    domain: "Food Tech",
    description: "India's largest food delivery and restaurant platform. Interviews focus on problem-solving, system design at scale, and product thinking.",
    interviewTypes: ["TECHNICAL", "HR", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "How would you design a food delivery tracking system?", sampleAnswer: "Real-time location tracking via WebSocket/SSE. Components: Order service, Driver location service (GPS updates every 5s), ETA calculation engine (graph-based routing + traffic + restaurant prep time), Push notification service. Store location data in Redis (fast writes). Use geospatial indexing for driver matching. Kafka for event streaming between services.", tips: "Think about the real-time aspect. Zomato tracks millions of deliveries. Mention handling GPS drift and battery optimization.", tags: ["System Design", "Real-time", "Geospatial"] },
      { category: "SYSTEM_DESIGN", difficulty: "HARD", question: "Design a restaurant recommendation system.", sampleAnswer: "Data: user preferences, order history, ratings, location, time, cuisine. Approach: collaborative filtering (users who ordered similar → recommend) + content-based (cuisine, price range match) + contextual (time of day, weather, trending). Architecture: Feature store → ML ranking model → Re-ranking (promotions, freshness). A/B test different models. Cold start: use demographics and popular items.", tips: "Zomato's recommendations drive revenue. Discuss cold start problem, exploration vs exploitation, and real-time personalization.", tags: ["System Design", "ML", "Recommendations"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is an index in a database and when would you use one?", sampleAnswer: "An index is a data structure (usually B-tree) that speeds up data retrieval at the cost of slower writes and extra storage. Use indexes on: columns in WHERE clauses, JOIN columns, ORDER BY columns, columns with high selectivity. Avoid on: frequently updated columns, low-cardinality columns (boolean), small tables. Composite index for multi-column queries.", tips: "Mention B-tree vs Hash index. Discuss the write performance trade-off. Very practical question.", tags: ["DBMS", "Performance", "SQL"] },
      { category: "HR", difficulty: "EASY", question: "Why Zomato?", sampleAnswer: "Zomato has fundamentally changed how 50M+ Indians eat. The engineering challenges — real-time delivery optimization, restaurant recommendations, handling 2M+ daily orders — are fascinating. I love that Zomato's culture values ownership and speed. The food-tech space in India is still growing, and I want to be part of building the infrastructure.", tips: "Mention specific Zomato features you use. Show knowledge of their Hyperpure, Blinkit integration.", tags: ["Company Knowledge"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Explain the concept of caching. What caching strategies exist?", sampleAnswer: "Caching stores frequently accessed data in faster storage (memory vs disk). Strategies: Cache-aside (app checks cache first, loads from DB on miss), Write-through (write to cache and DB simultaneously), Write-behind (write to cache, async to DB), Read-through (cache loads from DB on miss). Eviction: LRU, LFU, TTL. Tools: Redis, Memcached.", tips: "Mention cache invalidation as one of the hardest problems in CS. Discuss cache stampede and solutions.", tags: ["System Design", "Caching", "Performance"] },
    ],
  },
  {
    name: "Paytm",
    slug: "paytm",
    domain: "Fintech",
    description: "India's leading digital payments and financial services company. Interviews focus on scalable system design, coding, and fintech knowledge.",
    interviewTypes: ["TECHNICAL", "HR", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "How would you design a wallet system?", sampleAnswer: "Core: balance ledger with double-entry bookkeeping (every transaction creates debit and credit entries). Operations: add money, pay, transfer, refund. Use optimistic locking to prevent race conditions on balance. Implement daily reconciliation. Audit log for every transaction. Consider: KYC limits, transaction limits, fraud checks.", tips: "Paytm's wallet was their first product. Mention RBI regulations on prepaid instruments.", tags: ["System Design", "Fintech", "Payments"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the difference between authentication and authorization?", sampleAnswer: "Authentication verifies identity (who are you?) — login with username/password, OTP, biometrics. Authorization determines access (what can you do?) — role-based access control, permissions. Example: logging into your bank account is authentication; being allowed to transfer money (vs just view balance) is authorization. Auth flow: authenticate first, then authorize.", tips: "Mention OAuth 2.0, JWT tokens, RBAC. Paytm deals heavily with both.", tags: ["Security", "Web"] },
      { category: "HR", difficulty: "EASY", question: "What do you know about Paytm's products?", sampleAnswer: "Paytm started as a mobile wallet and expanded to: Paytm Payments Bank, Paytm Money (investments), Paytm Insurance, Paytm for Business (merchant solutions), and Paytm Mini Apps. They process over 1B+ monthly transactions. Recent focus: offline payments via QR codes, lending products, and insurance distribution.", tips: "Know the difference between Paytm wallet and Paytm Payments Bank. Mention their merchant ecosystem.", tags: ["Company Knowledge", "Fintech"] },
      { category: "SYSTEM_DESIGN", difficulty: "HARD", question: "Design a UPI payment system.", sampleAnswer: "Components: PSP App (Paytm) → UPI Switch (NPCI) → Remitter Bank → Beneficiary Bank. Flow: user initiates → PSP validates → NPCI routes → debit from sender's bank → credit to receiver's bank → response propagated back. Key considerations: 2-second SLA, idempotency, handle bank timeouts, reconciliation. Store: transaction log, dispute records. Security: device binding, UPI PIN encryption.", tips: "UPI is India's biggest fintech innovation. Understand the NPCI role. Discuss handling bank failures gracefully.", tags: ["System Design", "UPI", "Fintech"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "What is a message queue? When would you use one?", sampleAnswer: "A message queue is an async communication mechanism between services. Producer sends message → queue stores → consumer processes. Benefits: decoupling, load leveling, reliability. Use cases: email sending, payment processing, notifications, log processing. Popular: RabbitMQ (AMQP), Kafka (event streaming), AWS SQS. Kafka for high-throughput streaming; RabbitMQ for task queues.", tips: "Compare Kafka vs RabbitMQ. Mention dead letter queues and at-least-once vs exactly-once delivery.", tags: ["System Design", "Messaging", "Architecture"] },
    ],
  },
  {
    name: "Deloitte",
    slug: "deloitte",
    domain: "Consulting",
    description: "Big Four consulting firm with strong technology practice. Interviews focus on case studies, behavioral questions, and consulting frameworks.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL"],
    questions: [
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Walk me through a case: A retail company's profits are declining. How would you diagnose the problem?", sampleAnswer: "Framework: Revenue (price × volume) and Cost analysis. Questions: Is revenue declining or costs increasing? If revenue: which product lines? Which regions? New competitors? Pricing pressure? If costs: fixed or variable? Operational inefficiency? Supply chain issues? I'd segment the data, identify the biggest driver, then drill down. Hypothesis: if all regions declining equally, likely market/competitive issue; if one region, likely local factor.", tips: "Use structured frameworks (profitability = revenue - costs). Think out loud. Deloitte values structured thinking over the 'right' answer.", tags: ["Case Study", "Consulting Framework"] },
      { category: "HR", difficulty: "EASY", question: "Why consulting? Why Deloitte?", sampleAnswer: "Consulting offers variety — working across industries and problems keeps learning continuous. Deloitte specifically because of its technology-first approach (Deloitte Digital, AI/Cloud practice), strong presence in India, and emphasis on both strategy and implementation. Unlike pure-play tech firms, Deloitte lets me work at the intersection of technology and business.", tips: "Mention Deloitte's specific practices (Risk Advisory, Technology Consulting). Don't just say 'Big Four prestige.'", tags: ["Company Knowledge", "Consulting"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "Tell me about a time you led a team.", sampleAnswer: "STAR: Led a 5-member team for our database management course project. I organized the first meeting to divide roles based on strengths, set up weekly check-ins, and created a shared project tracker. When one member struggled with SQL queries, I organized a peer-learning session. We scored the highest in class and the professor used our project as an example.", tips: "Show leadership beyond delegation — mentoring, conflict resolution, and accountability.", tags: ["Leadership", "STAR"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is cloud computing? Explain IaaS, PaaS, SaaS.", sampleAnswer: "Cloud computing delivers computing resources over the internet on-demand. IaaS (Infrastructure as a Service): raw compute, storage, networking — you manage OS and apps (AWS EC2, Azure VMs). PaaS (Platform as a Service): managed runtime — you just deploy code (Heroku, App Engine). SaaS (Software as a Service): ready-to-use applications (Gmail, Salesforce).", tips: "Deloitte does cloud consulting. Know the major cloud providers and when clients choose IaaS vs PaaS vs SaaS.", tags: ["Cloud", "Architecture"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Describe a time you had to communicate a complex technical concept to a non-technical audience.", sampleAnswer: "STAR: During my internship, I had to explain our API architecture to the marketing team who needed to understand data flow for campaign tracking. I used an analogy of a restaurant: the API is the waiter (takes orders, delivers food), the database is the kitchen (stores and prepares data), and the frontend is the dining area. They understood immediately and could now articulate requirements clearly.", tips: "Deloitte consultants bridge tech and business daily. Show you can simplify without being condescending.", tags: ["Communication", "Consulting", "STAR"] },
    ],
  },
  {
    name: "KPMG",
    slug: "kpmg",
    domain: "Consulting",
    description: "Global Big Four firm with strong audit, tax, and advisory practices. Interviews include case studies, behavioral, and domain knowledge.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL"],
    questions: [
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Case: A bank wants to reduce customer churn by 20%. How would you approach this?", sampleAnswer: "Step 1: Define churn (account closure? inactivity?). Step 2: Segment customers by risk factors (age, balance, products used, complaints, tenure). Step 3: Analyze churned customers — what's common? Step 4: Predictive model to identify at-risk customers. Step 5: Interventions — personalized offers, proactive outreach, improved digital experience, loyalty programs. Step 6: Measure and iterate.", tips: "KPMG works heavily with BFSI clients. Show data-driven approach and mention cost of acquisition vs retention.", tags: ["Case Study", "BFSI", "Consulting"] },
      { category: "HR", difficulty: "EASY", question: "What interests you about KPMG's advisory practice?", sampleAnswer: "KPMG's focus on technology-driven advisory — particularly in cybersecurity, data analytics, and digital transformation — aligns with my skills. The opportunity to work with clients across BFSI, healthcare, and manufacturing means diverse problem exposure. KPMG's emphasis on integrity and quality resonates with how I approach work.", tips: "Know KPMG's specific service lines. Mention their Lighthouse (analytics) or cyber security practice.", tags: ["Company Knowledge"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is data analytics? What tools have you used?", sampleAnswer: "Data analytics is the process of examining data to find patterns, draw conclusions, and support decision-making. Types: descriptive (what happened), diagnostic (why), predictive (what will happen), prescriptive (what to do). Tools I've used: Python (pandas, matplotlib), SQL for querying, Excel/Power BI for visualization, basic machine learning with scikit-learn.", tips: "KPMG's Lighthouse practice is analytics-focused. Mention real projects where you used these tools.", tags: ["Analytics", "Tools"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "How do you prioritize tasks when everything seems urgent?", sampleAnswer: "I use the Eisenhower Matrix: categorize by urgency and importance. Urgent+Important: do immediately. Important+Not Urgent: schedule. Urgent+Not Important: delegate if possible. Neither: eliminate. In practice, during my final semester with exams, project deadlines, and placement prep, I time-blocked each day, tackled the highest-stakes items in my peak productive hours (morning), and said no to activities that didn't serve my goals.", tips: "Show a framework, not just 'I work harder.' Mention specific time management tools or techniques.", tags: ["Time Management", "Prioritization"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Give an example of when you had to adapt to change quickly.", sampleAnswer: "STAR: During my internship, the project scope changed from a desktop app to a web app mid-sprint due to client requirements. I had limited web dev experience, so I spent the weekend learning React basics, paired with a senior developer for two days, and delivered my assigned features on the revised timeline. The adaptability I showed led to a PPO offer.", tips: "KPMG consultants face constant change. Show you embrace it rather than resist it.", tags: ["Adaptability", "STAR"] },
    ],
  },
  {
    name: "Goldman Sachs",
    slug: "goldman-sachs",
    domain: "Investment Banking",
    description: "Global investment banking leader. Engineering interviews focus on DSA, system design, and quantitative problem-solving.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "HARD", question: "Implement a function to serialize and deserialize a binary tree.", sampleAnswer: "Serialize: preorder traversal, use 'null' for empty nodes, comma-separated. Deserialize: split by comma, use a queue, recursively build tree. Serialize(root): if null return 'null', return root.val + ',' + serialize(left) + ',' + serialize(right). Deserialize: dequeue value, if 'null' return null, create node, node.left = deserialize, node.right = deserialize.", tips: "Goldman asks harder DSA than most companies. Practice LeetCode medium-hard. Show clean, working code.", tags: ["DSA", "Trees", "Serialization"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "Explain concurrency vs parallelism.", sampleAnswer: "Concurrency: managing multiple tasks at once (time-slicing on single core) — like one person juggling multiple balls. Parallelism: executing multiple tasks simultaneously (multi-core) — like multiple people each holding a ball. Concurrency is about structure; parallelism is about execution. Python's GIL allows concurrency but limits true parallelism for CPU-bound tasks; use multiprocessing for parallelism.", tips: "Mention GIL in Python, goroutines in Go, or Java threads. Goldman builds high-performance trading systems that need both.", tags: ["Concurrency", "OS", "Performance"] },
      { category: "HR", difficulty: "EASY", question: "Why Goldman Sachs engineering?", sampleAnswer: "Goldman Sachs processes billions in transactions daily, requiring engineering that's both high-performance and fault-tolerant. The firm's investment in technology (GS Engineering has 25,000+ engineers) and platforms like Marquee and Transaction Banking show that Goldman treats engineering as a core business, not a support function. I want to build systems where milliseconds matter.", tips: "Goldman wants engineers who understand finance is now a tech business. Mention their open-source contributions (Legend, Alloy).", tags: ["Company Knowledge", "Finance"] },
      { category: "SYSTEM_DESIGN", difficulty: "HARD", question: "Design a real-time stock price feed system.", sampleAnswer: "Sources: exchange feeds (FIX protocol), market data vendors. Architecture: Feed handler → Normalizer → Message bus (low-latency, like Aeron/LMAX Disruptor) → Consumer services (trading engine, analytics, display). Key: sub-millisecond latency, ordering guarantees, multicast for distribution. Store: time-series DB (InfluxDB) for historical, in-memory for real-time. Handle: market hours, circuit breakers, data quality checks.", tips: "Goldman is a trading firm. Show understanding of low-latency systems. Mention UDP multicast, kernel bypass networking if you know them.", tags: ["System Design", "Finance", "Low-Latency"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Tell me about a time you worked with a difficult dataset or ambiguous requirements.", sampleAnswer: "STAR: In my data analytics project, the client's sales data had 30% missing values and inconsistent date formats. Instead of dropping rows, I analyzed the pattern of missingness, used appropriate imputation (mean for numerical, mode for categorical), standardized dates, and documented all assumptions. The resulting analysis helped identify a 15% revenue opportunity in an overlooked customer segment.", tips: "Goldman values quantitative thinking. Show you're comfortable with data ambiguity and can make justified assumptions.", tags: ["Data", "Problem-Solving", "STAR"] },
    ],
  },
  {
    name: "JP Morgan Chase",
    slug: "jp-morgan",
    domain: "Investment Banking",
    description: "World's largest bank by assets. JP Morgan's tech division is massive with focus on Java, system design, and financial technology.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL", "SYSTEM_DESIGN"],
    questions: [
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "What are design patterns? Explain Singleton and Observer.", sampleAnswer: "Design patterns are reusable solutions to common software design problems. Singleton: ensures only one instance of a class exists (e.g., database connection pool, logger). Implementation: private constructor, static instance, public getter. Observer: one-to-many dependency — when one object changes state, all dependents are notified (e.g., event listeners, stock price updates to multiple displays).", tips: "JP Morgan uses Java heavily. Know at least 5 design patterns. Mention thread-safe Singleton (double-checked locking or enum singleton).", tags: ["Design Patterns", "Java", "OOP"] },
      { category: "TECHNICAL", difficulty: "MEDIUM", question: "What is Spring Boot and why is it popular for enterprise applications?", sampleAnswer: "Spring Boot is a framework that simplifies Spring application development with auto-configuration, embedded servers, and opinionated defaults. Benefits: rapid development (starter dependencies), production-ready features (health checks, metrics), microservices support, large ecosystem (Spring Security, Spring Data, Spring Cloud). It reduces boilerplate and lets developers focus on business logic.", tips: "JP Morgan's backend is heavily Spring Boot. If you know Spring, mention specific features you've used.", tags: ["Java", "Spring Boot", "Enterprise"] },
      { category: "HR", difficulty: "EASY", question: "What do you know about JP Morgan's technology division?", sampleAnswer: "JP Morgan has 50,000+ technologists and invests $12B+ annually in technology. Key platforms: Atlas (cloud infrastructure), Athena (risk analytics), Onyx (blockchain-based payments). They use Java extensively and contribute to open source (Legend data management). The firm is also a leader in quantum computing research and AI/ML in trading.", tips: "JP Morgan is a tech company that happens to be a bank. Mention their open-source work and specific platforms.", tags: ["Company Knowledge", "Finance"] },
      { category: "SYSTEM_DESIGN", difficulty: "MEDIUM", question: "Design a transaction reconciliation system.", sampleAnswer: "Purpose: match internal transaction records with external bank/exchange records to find discrepancies. Architecture: Batch ingestion (internal + external data) → Matching engine (exact match on ID, fuzzy match on amount/date/counterparty) → Exception queue (unmatched/mismatched items) → Dashboard for operations team. Rules engine for matching logic. Daily and intraday reconciliation. Alert on break thresholds.", tips: "Reconciliation is critical in banking. Discuss handling edge cases: duplicate records, partial matches, timing differences.", tags: ["System Design", "Finance", "Data Processing"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "How do you ensure code quality in your projects?", sampleAnswer: "Multiple layers: meaningful variable names and clean code principles, unit tests with good coverage (aim for 80%+), code reviews (I always request reviews even for small changes), linting and static analysis (ESLint, SonarQube), integration tests for critical paths. I also document complex business logic and maintain a clear PR description for reviewers.", tips: "JP Morgan values code quality in financial systems. Mention testing, reviews, and documentation practices.", tags: ["Code Quality", "Best Practices"] },
    ],
  },
  {
    name: "Accenture",
    slug: "accenture",
    domain: "IT Consulting",
    description: "Global professional services company with massive scale. Accenture interviews focus on aptitude, communication, and basic technical skills.",
    interviewTypes: ["TECHNICAL", "HR", "BEHAVIORAL"],
    questions: [
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the software development life cycle (SDLC)?", sampleAnswer: "SDLC is the process of planning, creating, testing, and deploying software. Phases: 1) Requirement gathering, 2) System design, 3) Implementation (coding), 4) Testing, 5) Deployment, 6) Maintenance. Models: Waterfall (sequential), Agile (iterative), Spiral (risk-driven), V-Model (verification + validation). Modern teams mostly use Agile (Scrum/Kanban) for flexibility.", tips: "Accenture works on enterprise projects. Know Waterfall vs Agile comparison thoroughly. Mention DevOps as the evolution.", tags: ["SDLC", "Process"] },
      { category: "TECHNICAL", difficulty: "EASY", question: "What is the difference between Python and Java?", sampleAnswer: "Python: interpreted, dynamically typed, concise syntax, great for data science/scripting/ML, slower execution. Java: compiled to bytecode (JVM), statically typed, verbose but explicit, great for enterprise/Android/large systems, faster execution. Python: `print('hello')`. Java: needs class, main method, System.out.println. Choose Python for rapid development, Java for performance-critical enterprise apps.", tips: "Accenture uses both. Be fair in comparison — don't trash either language.", tags: ["Programming Languages", "Comparison"] },
      { category: "HR", difficulty: "EASY", question: "Why Accenture?", sampleAnswer: "Accenture's scale (750,000+ employees, projects in 120+ countries) offers unmatched exposure to diverse industries and technologies. The 'New IT' strategy focusing on cloud, AI, and digital transformation means I'll work on cutting-edge projects. Accenture's investment in training (500,000+ courses on Percipio) shows they invest in employee growth. The Bengaluru Innovation Hub is particularly exciting.", tips: "Mention specific Accenture initiatives. Their size is a strength — frame it as learning opportunity, not bureaucracy.", tags: ["Company Knowledge"] },
      { category: "HR", difficulty: "MEDIUM", question: "Are you open to working in any domain assigned to you?", sampleAnswer: "Yes, I'm open to working across domains. I believe every industry — whether BFSI, healthcare, retail, or telecom — presents unique technical challenges that help me grow. In consulting, domain flexibility is an asset. I'm particularly interested in [your preference], but I see value in gaining cross-industry experience early in my career.", tips: "Accenture assigns you to projects based on client needs. Never limit yourself to one domain in the interview.", tags: ["Flexibility", "Domain"] },
      { category: "BEHAVIORAL", difficulty: "EASY", question: "Tell me about your strengths and weaknesses.", sampleAnswer: "Strength: I'm a fast learner who connects theory to practice quickly. In my internship, I went from zero React knowledge to building a production feature in 10 days. I attribute this to active learning — I build while I learn, not after. Weakness: I tend to over-research before starting. I've been using timeboxing — giving myself a fixed research window before jumping into implementation.", tips: "Pick a genuine strength with a concrete example. For weakness, show self-awareness and active improvement.", tags: ["Self-Awareness", "Strengths"] },
      { category: "BEHAVIORAL", difficulty: "MEDIUM", question: "Describe a situation where you had to learn a new technology quickly.", sampleAnswer: "STAR: For a hackathon, my team decided to use Flutter for a mobile app — a framework I'd never touched. I had 3 days before the event. I completed the official codelabs, built a small todo app, and studied Dart syntax. During the hackathon, I was productive from hour one. We built a health tracking app and won the 'Best UI' award. Key: I focused on essentials (widgets, state management) and skipped advanced topics.", tips: "Accenture consultants need to learn new tech constantly. Show structured, efficient learning ability.", tags: ["Learning", "Adaptability", "STAR"] },
    ],
  },
];

async function main() {
  console.log("Seeding mock interview companies and questions...\n");

  for (const companyData of companies) {
    console.log(`  Creating/updating: ${companyData.name}`);

    const company = await prisma.mockCompany.upsert({
      where: { slug: companyData.slug },
      update: {
        name: companyData.name,
        domain: companyData.domain,
        description: companyData.description,
        interviewTypes: companyData.interviewTypes,
      },
      create: {
        name: companyData.name,
        slug: companyData.slug,
        domain: companyData.domain,
        description: companyData.description,
        interviewTypes: companyData.interviewTypes,
      },
    });

    // Delete existing questions to avoid duplicates on re-seed
    await prisma.mockQuestion.deleteMany({ where: { companyId: company.id } });

    // Create questions
    for (let i = 0; i < companyData.questions.length; i++) {
      const q = companyData.questions[i];
      await prisma.mockQuestion.create({
        data: {
          companyId: company.id,
          category: q.category,
          difficulty: q.difficulty,
          question: q.question,
          sampleAnswer: q.sampleAnswer,
          tips: q.tips,
          tags: q.tags,
          order: i + 1,
        },
      });
    }

    console.log(`    -> ${companyData.questions.length} questions created`);
  }

  const totalCompanies = await prisma.mockCompany.count();
  const totalQuestions = await prisma.mockQuestion.count();
  console.log(`\nDone! ${totalCompanies} companies, ${totalQuestions} questions seeded.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
