import { LegalPage } from "@/components/legal";
import { pageMeta } from "@/lib/seo";

export const metadata = pageMeta({ title: "Terms of service", description: "The terms that govern use of CorpGurus by trainers, companies and training partners: accounts, requirements, work orders, payments, escrow, subscriptions and acceptable use.", path: "/legal/terms" });

export default function TermsPage() {
  return (
    <LegalPage title="Terms of service" effective="1 October 2026" current="terms"
      intro={<p>These terms are an agreement between you and CorpGurus (“CorpGurus”, “we”, “us”), operated from India, covering the CorpGurus website, apps and API (the “Platform”). By creating an account or using the Platform you accept them. If you use the Platform for a company, you confirm you are authorised to bind that company.</p>}
      sections={[
        { id: "platform", title: "What CorpGurus is", body: <><p>CorpGurus is a marketplace and professional network that connects companies and training partners (“Companies”) with independent corporate trainers (“Trainers”). Companies post training requirements; Trainers apply; the parties agree terms in a work order on the Platform.</p><p>CorpGurus is not a party to the training engagement itself, does not employ Trainers, and does not guarantee the outcome of any training. Trainers are independent contractors responsible for their own taxes, GST registration and compliance.</p></> },
        { id: "accounts", title: "Accounts and eligibility", body: <><ul><li>You must be at least 18 and able to enter contracts under Indian law.</li><li>Keep your credentials confidential; you are responsible for activity on your account.</li><li>One person may hold one Trainer account. Companies may add team members; the company owner is responsible for members’ actions.</li><li>Information you provide (certifications, experience, company details, GSTIN) must be accurate and current. We may ask for supporting documents before showing a verified badge.</li></ul></> },
        { id: "content", title: "Requirements, applications and content", body: <><ul><li>Requirements must describe genuine training needs. Job listings for employment, unrelated services, or requirements that discriminate on prohibited grounds are not allowed.</li><li>Applications, comments, posts, recommendations and messages must be truthful and professional. We may remove content that is misleading, abusive, infringing or off-topic, and suspend accounts that repeatedly breach these rules.</li><li>You retain ownership of content you post. You grant CorpGurus a non-exclusive, worldwide licence to host, display and distribute it on the Platform and in Platform marketing (for example, a public profile card) for as long as it is on the Platform.</li><li>Day rates set by Trainers are shown only to signed-in Company accounts. Do not scrape, copy or republish Platform data.</li></ul></> },
        { id: "engagements", title: "Work orders, delivery and ratings", body: <><ul><li>A work order sent by a Company and accepted by a Trainer, including the typed signatures recorded on it, is a binding agreement between those two parties for the dates, rate, deliverables and terms it states.</li><li>Cancellation and reschedule terms are those written in the work order. If none are written, the cancellation policy in our <a href="/legal/refunds" className="text-cyan hover:underline">refunds and cancellations</a> document applies by default.</li><li>Both parties may rate each other after an engagement. Ratings must reflect a genuine experience. We may remove ratings that breach these terms but do not otherwise edit them.</li><li>Take engagements you found on CorpGurus through the Platform (work order and, where used, escrow). Circumventing the Platform to avoid fees or protections may lead to account suspension.</li></ul></> },
        { id: "payments", title: "Payments, escrow and invoices", body: <><ul><li><strong>Direct payment.</strong> Unless escrow is used, the Company pays the Trainer directly against the Trainer’s invoice. CorpGurus is not responsible for collection.</li><li><strong>Escrow (managed payment).</strong> A Company may fund the work-order amount with CorpGurus after acceptance. We hold it and release it to the Trainer when the Company confirms delivery, less the platform fee shown before funding (currently 5%). Payouts are made to the bank details the Trainer has on file within two working days of release. Refunds to Companies follow the refunds document. Funds held in escrow do not earn interest for either party.</li><li><strong>Payment processing</strong> is provided by Razorpay (INR) and Stripe (USD) under their own terms. We do not store card details.</li><li>Invoices generated on the Platform are the Trainer’s documents; the Trainer is responsible for their GST treatment and accuracy.</li></ul></> },
        { id: "subscriptions", title: "Subscriptions", body: <><ul><li>Paid plans (Trainer Pro, Company Growth, Training Partner) renew automatically monthly or yearly until cancelled. Prices are shown before purchase and exclude GST unless stated.</li><li>Cancel any time from Settings → Plan &amp; billing. Benefits continue to the end of the paid period. Refunds are described in the refunds document.</li><li>We may change plan prices or features with at least 30 days’ notice by email; changes apply from your next renewal.</li></ul></> },
        { id: "api", title: "API and webhooks", body: <><ul><li>API keys are issued to Companies for integrating their own systems. Keep keys secret; you are responsible for calls made with them.</li><li>Rate limits apply. Do not use the API to bulk-export Trainer data or to build a competing directory.</li><li>We may change or deprecate API endpoints with reasonable notice.</li></ul></> },
        { id: "acceptable-use", title: "Acceptable use", body: <><p>You must not: post false certifications or impersonate others; harass or discriminate; send spam or unsolicited marketing through messages; upload malware; attempt to access other accounts or data; interfere with the Platform’s operation; or use the Platform for anything unlawful.</p></> },
        { id: "ip", title: "Intellectual property", body: <><p>The Platform, its design, code, trademarks and CorpGurus content are owned by CorpGurus and its licensors. Training materials exchanged between a Company and a Trainer belong to whoever the work order says; if it is silent, each party keeps what it created.</p></> },
        { id: "liability", title: "Disclaimers and limitation of liability", body: <><p>The Platform is provided “as is”. We verify certifications and company domains with reasonable care but do not warrant that any profile, requirement or content is accurate or that any engagement will be delivered. To the fullest extent permitted by law, CorpGurus is not liable for indirect or consequential loss, and our total liability to you for any claim in a 12-month period is limited to the fees you paid us in that period, or ₹10,000, whichever is greater. Nothing here limits liability that cannot be limited under Indian law.</p></> },
        { id: "termination", title: "Suspension and termination", body: <><p>You can close your account from Settings. We may suspend or close accounts that breach these terms, after notice where practical. Work orders already accepted, escrow funds and invoices are handled according to their own terms after termination.</p></> },
        { id: "changes", title: "Changes to these terms", body: <><p>We may update these terms. Material changes are announced on the Platform and by email at least 14 days before they take effect. Continued use after that date means you accept the new terms.</p></> },
        { id: "law", title: "Governing law and disputes", body: <><p>These terms are governed by the laws of India. Disputes are subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka, after a good-faith attempt to resolve them with us through <a href="mailto:hello@corpgurus.com" className="text-cyan hover:underline">hello@corpgurus.com</a>.</p><p>Grievance officer (Information Technology Rules, 2021): reachable at the same address; we acknowledge complaints within 24 hours and resolve them within 15 days.</p></> },
      ]}
    />
  );
}
